defaults:
  - arch: trm
  - _self_

hydra:
  output_subdir: null

entity: "trelis"

# Data path
data_paths: ['data/arc-manual-eval-aug-1000']
data_paths_test: ['data/arc-manual-eval-aug-1000']

load_checkpoint: null
checkpoint_path: null

arch:
  lora_rank: 1
  lora_alpha: 16.0
  lora_dropout: 0.0
  lora_train_base: false
  lora_train_bias: false

evaluators:
  - name: arc@ARC

# Dataloader tweaks for Kaggle runtime
dataloader_num_workers: 1
dataloader_prefetch_factor: 4
dataloader_pin_memory: true
dataloader_persistent_workers: false

# Hyperparams - Training
global_batch_size: 24

epochs: 6250
eval_interval: 6250
checkpoint_every_eval: True
checkpoint_every_n_steps: null

lr: 0.36125e-5
lr_min_ratio: 1.0
lr_warmup_steps: 200

# Standard hyperparameter settings
beta1: 0.9
beta2: 0.95
weight_decay: 0.1
puzzle_emb_weight_decay: 0.1

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 0.36125e-3

seed: 0
min_eval_interval: 0

ema: False
ema_rate: 0.999
freeze_weights: False
